name: Build and publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: vantage-pro-weather
        dockerfile: Dockerfile
